### ISSUE TITLE
Does the size_t & uint64_t really necessary in opencl kernel.cl?

### ISSUE THREAD

**Issue by lygstate** [pytorch/glow#1187]
First of all NVIDIA CUDA OpenCL doesn't support size_t.
Besides, When compiling the executable under 32 bit application, 
uint64_t about to be another issue:0
cause in kernel
```
typedef struct {
  cl_uint64_t n; // Number of samples
  cl_uint64_t h; // Height
  cl_uint64_t w; // Width
  cl_uint64_t c; // Number of channels
} ShapeNHWC;
```
but in C++

```
struct ShapeNCHW {
  size_t n; // Number of samples
  size_t c; // Number of Channels
  size_t h; // Height
  size_t w; // Width
```

There is inconsistence between OpenCL kernel & C++ code about size_t /uint64_t.
We may need to define a fixed coding style about size_t & uint64_t.

**Comment by lygstate** [comment]
I suggest to add glow_size_t that can be controlled by use.
For some small model, size_t be uint32_t are enough, but for some big
model, we need uint64_t.

**Comment by opti-mix** [comment]
OpenCL kernels should use only fixed width types in method signatures and never size_t, as its width is platform-dependent. For the time being, we should probably use uint64_t in ShapeNCHW and the like to match the OpenCL side.

**Comment by nadavrot** [comment]
@lygstate The problem that we ran into was that size_t on the device did not match the size of size_t on the host.

**Comment by lygstate** [comment]
@nadavrot thats why I add a predefined macro in my request

**Comment by lygstate** [comment]
@opti-mix Does uint64_t would affect the OpenCL performance?
cause it's a really big number. For some embbed OpenCL platform.
do uint64_t arithmatic would be costy, so I would suggest the size couuld be configurable.

**Comment by opti-mix** [comment]
@lygstate get_global_id and the like return `size_t` according to the OpenCL specification. But size_t  could be < 64bit on some OpenCL platforms.

I checked the code of kernels. We currently seem to pass integers as 32bits in signatures. But in  inside function bodies we use size_t, ssize_t and inside ShapeNCHW we use 64bits. So, in principle, we could use smaller fixed-width types there. 

> do uint64_t arithmatic would be costy, 

We currently use uint64_t only in ShapeNCHW when we pass the struct as kernel argument. Inside the kernels they are typically assigned to size_t variables.

Have you really seen any performance issues because of this?

> so I would suggest the size could be configurable.

We could do this. PRs are welcome!

In any case, the fact you mentioned about the current inconsistency with regards to ShapeNHWC definitions in kernels.cl and in host's C++ is really an issue. They should be made consistent. The obvious fix would be to make the C++ definition use uint64_t for now. Once we provide a way to configure the width, we should use that configured width on both sides.

**Comment by lygstate** [comment]
I have already trying to modify the c++ code to be consistentence with opencl， but cause a lot of errors， so I prefer modify the opencl code first， and after all， we use configured size in one step

**Comment by pjaaskel** [comment]
https://github.com/pytorch/glow/pull/3542 this PR touches this since it changes "size_t" to a Glow-specific "dim_t" which can be fixed to 64b or 32b across Glow.
