### ISSUE TITLE
Need to implement channel-wise quantized fullyconnected node.

### ISSUE THREAD

**Issue by nadavrot** [pytorch/glow#1402]
One technique to improve the accuracy of quantized fullyconnected operations is channel-wise quantization. In this technique the activations remain regular quantized activations, but the FC weights are quantized with special per-channel information. PyTorch has support for this operator[1] 

To implement this you will need to do the following:
1. Add new target independent node to the Interpreter and CPU backends.
2. Implement the IR-lowering for the new target-independent FC. 
3. Implement a special kind of FC-quantization and lowering that lowers the FC into row-wise FC. This method will need to inspect the weights and extract the channel-specific information. 

[1] - https://github.com/caffe2/caffe2/blob/master/caffe2/operators/fused_rowwise_8bit_conversion_ops.cc

@rdzhabarov @jfix71

**Comment by rdzhabarov** [comment]
The plan looks good to me, I think we'd need to have a way to control channel-wise quantization through some CLI flag as well. We could also extend this issue to cover Conv, but FC would have higher priority.

**Comment by nadavrot** [comment]
@beicy FYI

**Comment by rdzhabarov** [comment]
@beicy feel free to grab this and I'm happy to help with anything related to this issue. Otherwise, I'll tackle this some time in between ONNXIFI work.

**Comment by beicy** [comment]
The design for this issue is described as follows:  

**1. Two new nodes are introduced for row-wise quantization** 

**- 1.1 FloatToFused8BitRowwiseQuantize**
The input of this op is a 2-D tensor (i.e. N * M) with float type for each element.  The output is a 2-D tensor with int8_t type. The shape of the output is (N * (M + 8)). For each row of the output, the stored data layout is : 

| ... quantized int8 data...|scale (float)|offset (int32_t)| 
| ...... M...bytes.................|.....4B..........|....4B................|

The **_scale_** and **_offset_** are chosen based on the min and max of each row of the input tensor. After the **_scale_** and the **_offset_** of each row is generated, the input data of this row are quantized and stored in the first M bytes of each output row.

**- 1.2 Fused8BitRowwiseQuantizedToFloat**
This is to de-quantize the 1.1 op. The input is a 2-D tensor (N * (M+8)) with int8_t type and the output is a 2-D tensor (N * M) with float type.
**Notes**:  I was thinking about using 3 separate tensors to represent quantized data, offsets, and scales. But if later we would like to row-wise quantize more inputs, the number of the params would be increased. Therefore, I used the similar way as the following Caffe2 op does: 
https://caffe2.ai/docs/operators-catalogue.html#floattofused8bitrowwisequantized

**2.  RowWiseFullyConnected Node**
Previously, for a FC node, if it is quantized-able, the whole node is quantized and then lowered into _matmul_ + _add_. In this PR, if a FC node is quantize-able (for Interpreter and CPU backends), we generate the following flow and no more lowering optimization:

![image](https://user-images.githubusercontent.com/37386895/45527745-1f1e7c80-b792-11e8-80ee-a1720310776e.png)

In the above picture, some of the nodes are explained as follows: 
**Reshape**  : flatten the input of original FC
**Transpose** :  since the weights of FC is stored in transposed shape, transpose it back.
**FloatToFused8BitRowwiseQuantize** :  row-wise quantization of weights of original FC.
**RowWiseFullyConnected** :    row-wise FC
 
**3. Interpreter Backend support.**

**4. CPU Backend support.**

**5.  Unittest for   FloatToFused8BitRowwiseQuantize and Fused8BitRowwiseQuantizedToFloat.** 
 The current unittests for quantization FC can be used to test the row-wise FC since row-wise FC is enabled by default. 

**6. Adding flag to control row-wise.**

**Comment by nadavrot** [comment]
Thank you for the great writeup @beicy . 

I have a question about FloatToFused8BitRowwiseQuantize. Why do we need to implement this as a new node? I assumed that we could just replace FC with RWFC and along the way convert the weights into some opaque tensor format, similar to how we do with our DKKC convolutions. Why do we need a multi-node solution? In any case we would need to implement the quantization procedure in the optimizer because we won't want to quantize the weights at runtime. Is there a strong requirement to support dynamically computed weights? @jspark1105

**Comment by beicy** [comment]
@nadavrot For regular quantization node, the scale and offset are given and carried by "struct Type" of the quantized tensor. In row-wise quantization, for each row of the tensor to be quantized, there is one (scale, offset) pair should be calculated by max and min. Since I don't want to modify the "struct Type", the "FloatToFused8BitRowwiseQuantize" is used to generate the scales, offsets and the quantized data. 
Do you mean we should row-wise quantize the weights at compiler time, and pass the quantized weights directly to RWFC?

**Comment by beicy** [comment]
@nadavrot I see. I will double check where row-wise quantization could be used. If it is only used for constant like weights, we don't need this quantization at runtime :)

**Comment by jspark1105** [comment]
Row-wise quantization has been used for constants weights in the cases I've seen.

**Comment by beicy** [comment]
Thanks @jspark1105 . Then this FloatToFused8BitRowwiseQuantize node is not necessary in Glow.

**Comment by beicy** [comment]
@rdzhabarov Thanks for letting me know the ONNX/C2 loader requirement. If the separation format is convenient for the further work,  let's separate the quantized data and scales and offsets :)

**Comment by rdzhabarov** [comment]
@beicy they do not have that format for row-wise quantization, but looking at general quantization support, that's the direction they are moving. Even for normal quantization, scale and offset are comming from a separate params to the Op.

**Comment by artemrakhov** [comment]
I'm wondering if we can have a better name for `RowWiseFullyConnected` node. Should not capitalize W to match Caffe2's row-wise op. And it's not clear from the name that it has something to do with quantization. How about `RowwiseQuantizedFullyConnected`?

**Comment by beicy** [comment]
@rdzhabarov Our profiling doesn't support it yet. Will add it.

**Comment by beicy** [comment]
@rdzhabarov Our quantization procedure doesn't support it yet -- just do the regular FC quantization. We should enable rowwise quantization under some flag's control.

**Comment by nadavrot** [comment]
Can we close this issue?

**Comment by ayermolo** [comment]
I was looking at implementation of this. For weights scale/offset are computed per filter/channel, but for bias only one is computed for entire vector/all channels. Is there a reason scale/offset wasn't computed per channel for biases? Not worth it in terms of improved accuracy, design decision limiting memory usage for constant tensor?
In this paper, https://arxiv.org/pdf/1806.08342.pdf, it mentions per channel weight quantization can improve accuracy. It doesn't really mention biases. I would venture a guess since each entry in bias vector corresponds to particular channel, it should also be quantized per channel?

**Comment by csummersea** [comment]
Bias will be one vector for one batch. If we have per filter/channel quantization for bias, we will end up with each bias parameter associated with one scale/offset parameters, which don't make much sense. As we will do int32 accumulation, we can increase the precision for the accumulation with bias also if the quantized bias are not accurate enough.

**Comment by jspark1105** [comment]
@ayermolo in addition to the overhead explained by Summer, per channel quantization for bias also doesn't help accuracy much because bias is usually quantized in int32 (it's small so it's ok to store them in 32-bit). I believe this is also the case in Glow.

**Comment by beicy** [comment]
Yes, in Glow, the bias is quantized in int32.

**Comment by ayermolo** [comment]
Ah yeah makes sense, and in retrospect quite obvious. Thanks.
