### ISSUE TITLE
Issue for quantized max pooling in the CPU backend (?)

### ISSUE THREAD

**Issue by tlepley-cadence** [pytorch/glow#1452]
My understanding is that in Glow the quantization parameters, scale/offset, are computed per tensor. Inputs and outputs tensors of an operator can then have different scales/offsets, and this needs to be handled by Glow at code generation (LLVM IR generation for the CPU backend).
In AveragePooling, I see that both input and output quantization parameters are used for the LLVM IR generation. 
But for MaxPooling, there is no specific code for the quantized version in `generateLLVMIRForInstr`. This implicitly means that the quantization parameters of the output tensor are assumed to be the same as the input tensor, what I think is not correct.

**Comment by rdzhabarov** [comment]
As of now, the way Quantized MaxPooling is handled in Glow is the following. We assume that the output scale/offset is the same as the input, but add RescaleNode right after MaxPool to make sure that values are compatible with the profiled range (from the MaxPool) we have on the quantization profiling step.

We could allow MaxPool to have different {s,0} for the output param but that's going to be an optimization as in any case we perform conversion to the right range later.

**Comment by tlepley-cadence** [comment]
@rdzhabarov Thanks for the explanation. Is it a general rule to add a `RescaleNode` for  handling the outputs, or there is a operator by operator decision made in Glow. And in this case, it it described somewhere ?

**Comment by rdzhabarov** [comment]
> Is it a general rule to add a RescaleNode for handling the outputs, or is it an operator by operator decision made in Glow

Not really a general rule (and in some cases that could lead to accuracy loss), but for some nodes we've been historically doing that. For MaxPool this is OK, since we work on int8 input numbers and would need to rescale it to a different {s,o} either as part of the operator itself or as a next step anyway (currently processed in a next step in the Rescale node).

> is it described somewhere ?
I do not think there are docs covering this specific case (concrete steps for conversion of fp32 node to int8 node). But you can get a sense of how this is done by looking at https://github.com/pytorch/glow/blob/master/lib/Quantization/Quantization.cpp#L126.
When a node needs to consume the output of MaxPool it'll make sure that {s,o} are set according to profiled data and that procedure will introduce the Rescale node.

**Comment by rdzhabarov** [comment]
@tlepley-cadence any objections to close this issue?

**Comment by nadavrot** [comment]
@rdzhabarov Do we check in the verifier that the input and output integer type of MaxPool match?

**Comment by rdzhabarov** [comment]
I do not think so, but we do not provide an API to set arbitrary output type of MaxPool.

**Comment by nadavrot** [comment]
@rdzhabarov I think that we should ensure somehow that the IR and the implementation match. It sounds like at the moment the backend makes an assumption that the IR does not guarantee.

**Comment by tlepley-cadence** [comment]
@rdzhabarov please feel to close this issue. There is indeed a `rescalequantized` instruction after each `maxpool` instruction in the low level IR.

**Comment by rdzhabarov** [comment]
Added checks to the verifier, closing this issue.
