### ISSUE TITLE
Does glow support layer fusion? Just like TensorRT does.

### ISSUE THREAD

**Issue by QiJune** [pytorch/glow#1549]
For example, conv + bias + relu can be fusion into one kernel in the inference stage. Does glow support such optimization? Thanks!

**Comment by nadavrot** [comment]
@QiJune The CPU backend does operator fusion. For example, the RELUs and merged with the following add nodes to create an efficient pattern. The OpenCL is not designed to be a high-performance implementation, so it does not have the optimizations that the CPU backend has. 

It's really easy to add new fusion operations. Take a look at the code in Transform.cpp in the CPU backend. This is where graph-level fusion happens for this specific backend. We also have target independent operations.

**Comment by QiJune** [comment]
@nadavrot Thanks for the explanation!
If I want to add new fusion operations or some target-dependent optimization, there are two things to do:

1. Add new optimization rules to modify Nodes, such as Merge/Transform/etc
2. Add corresponding C source code implementation

Is my understanding right? Thanks!

**Comment by jfix71** [comment]
@QiJune The steps to do operator fusion (e.g. fuse operator `A` and `B`, where `A` has a single user `B`) for some backend `X` would be:

1. Add a backend-specific Node "`FusedAB`" to `XSpecificNodes.h`, and a corresponding backend-specific Instruction "`FusedAB`" to `XSpecificInstrs.h`. Note that the `FusedABInst` needs to be marked with `autoIRGen()` so that the node is automatically IRGen'd to the instruction, as we currently do not support backend-specific IRGen.

2. Add logic to `XBackend::transformPreLowering()` or `XBackend::transformPostLowering()` (or both) depending on when you want to do the transformation. This logic would look for the pattern of nodes you want to fuse (`A` with a single use by `B`), and replaces all uses of the result of `B` with the new backend-specific `FusedABNode`.

3. Have your backend `X` implement `FusedABInst`. For example, for the OpenCL backend, this would mean adding a case to enqueue a kernel for the `FusedABInst` to `OpenCLFunction::execute()`, and then adding the corresponding kernel in `kernels.cl`.

**Comment by nadavrot** [comment]
@QiJune @jfix71 We should probably add the instructions to our docs.

**Comment by QiJune** [comment]
@nadavrot @jfix71 Thanks a lot! It really helps.

**Comment by nadavrot** [comment]
@QiJune Would you be interested in working on #1550 ?

**Comment by QiJune** [comment]
@nadavrot Yes, I am glad to work on #1550. 
Since @jfix71 has already list the steps adding a new target-specific node, which can be moved to the document directly. I wondering if I should also add an example of new target-specific node to make the doc more clear, such as conv + bias + relu fusion node.

**Comment by QiJune** [comment]
@nadavrot I have fire a pull request #1569 , please kindly help review it. Thanks!

**Comment by nadavrot** [comment]
@QiJune Thank you for doing this work!

**Comment by nadavrot** [comment]
This task is complete. Closing.

**Comment by soumyarooproy** [comment]
👍
