### ISSUE TITLE
[GraphOptimizer] Remove unnecessary NHWC-NCWH transposes.

### ISSUE THREAD

**Issue by jfix71** [pytorch/glow#1640]
In Shufflenet we have unnecessary transposes between NCHW and NHWC. We transpose to NCHW, then do some shuffling of the C dimension (via Reshape-Transpose-Reshape), then transpose again back to NHWC. This is unnecessary -- we can remove the transposes between NCHW and NHWC, and then modify the Dims/Shuffle of the Reshape-Transpose-Reshape to shuffle the C dimension.

Such a subgraph from Shufflenet can be seen here:
<img width="169" alt="shufflenet_subgraph" src="https://user-images.githubusercontent.com/1198212/45479079-29b72280-b74e-11e8-807a-171aaacf1461.png">

**Comment by rdzhabarov** [comment]
@jackm321, this would be also interesting, you'll get a sense of how high-level graph optimizations are implemented in Glow and implement one more. You'd also touch model loader part as well as some debugging instrumentation as to how to dump graphs etc.

Let me know if you'd like to tackle this one.

**Comment by jackm321** [comment]
[shufflenetDAG.pdf](https://github.com/pytorch/glow/files/2559607/shufflenetDAG.pdf)
From looking at the whole graph this seems to happen a lot (16 times I think) so fixing this should remove 32 transposes

**Comment by jackm321** [comment]
To summarize a discussion with @jfix71, @rdzhabarov, and I, this seems to be a little bit difficult to make a general solution to. It would be nice if we could see a transpose in the graph and walk upwards through a series of single-output nodes in the graph or even a dag to look for the opposite transpose (as in the first and last transposes in the picture above) and then remove them and transform the nodes in the middle appropriately. However it seems difficult to do this final step of transforming the nodes in the middle appropriately because some additional knowledge is required about how to transform the specific nodes in the middle (or if it's even possible for those nodes).
As an example, in the case here the next node after the first transpose is a reshape and we can tell in this case which dimension is getting split up because all other dimensions match except for one of them so we can tell how to modify this reshape if we were to remove the preceding transpose however if for example multiple dimensions were changed this reasoning would not be possible. Therefore a general solution to this is probably not straightforward so we'll focus on a solution to the more narrow problem depicted here of alternating transposes and reshapes where the external transposes together form the identity. To do this we will look for this exact pattern in the graph and replace it with the more optimal pattern. If there is a more general solution to this that someone sees please let me know and we can try that as well but to begin with we'll just reproduce this specific problem in a unit test and fix it and then try to generalize from there if possible.

**Comment by jfix71** [comment]
@jackm321 Thanks for the analysis! Overall I think it makes sense to pattern match this reshape-transpose-reshape pattern and sink the transpose below it. 

However just to note, one alternative here could be to add a node for `ChannelShuffle` so that `sinkCode()` better understands what's happening -- it would see `TransposeNHWC2NCHW-ChannelShuffle-TransposeNCHW2NHWC` and more easily understand how to modify the `ChannelShuffle's` parameters. Later on we would lower `ChannelShuffleNode` to `Reshape-Transpose-Reshape`. Of course, adding more nodes adds complexity to other parts of the compiler, so it's not necessarily a better idea -- there's a tradeoff here.

**Comment by jackm321** [comment]
@jfix71 I this is a good point, I thought about this approach as well (adding a `ChannelShuffleNode`). I feel like I don't have enough context yet to know which solution will be better overall. I think this specific GraphOptimization might be cleaner with a new node but as you said it may add more complexity in other places. I currently have a working solution to this specific issue that doesn't involve adding a new `ChannelShuffleNode` but if people think it would overall be better to have that new node I can add it and implement the transpose sinking with that.

**Comment by jfix71** [comment]
@jackm321 In this case I think it makes sense to not add a new node because we can somewhat easily determine what the `ChannelShuffle's` parameters were from the `Reshape-Transpose-Reshape`.
