### ISSUE TITLE
Optimization pipeline design with more backend control

### ISSUE THREAD

**Issue by jfix71** [pytorch/glow#1641]
Right now we have target-independent optimizations that may or may not benefit the backend executing the graph, and may even degrade performance. We need to allow the backend we are targeting have more control over what optimizations are performed.

For example, the GraphOptimizer's small matrix multiplication/batched add merging optimizations (`mergeMatMul()`/`mergeBatchedAdd()`) may not be beneficial (https://github.com/pytorch/glow/issues/1494).

Another example is the GraphOptimizer's `optimizePool()`, where we swap `RELU -> MaxPool` to `MaxPool -> RELU`. If the original subgraph is `Conv -> RELU -> MaxPool`, backends may prefer to vertically fuse `Conv -> RELU` into a single `ConvRELU` instead of  swapping the order of the `RELU` and `MaxPool`. So this optimization might be counterproductive/may prevent fusion from occurring.

Also related to https://github.com/pytorch/glow/pull/1633.

**Comment by QiJune** [comment]
Maybe we need to construct a cost model for each backend to analyze the cost of potential optimization.

If you give some hardware information and some `Instruction`, the cost model can return a cost number. The interface can be like this:

```
size_t getCost(const Backend& b, std::vector<Instruction>& is)
```
For each step optimization, GraphOptimizer will calculate a cost to decide whether add it or not. With iterative query on the cost model, maybe the globally optimial solution.

I am not sure if we can construct a such accurate cost model for each backend. And what hardware information should be get to construct such cost model?

**Comment by aturetsk** [comment]
Another thing we need to take into account is quantization.
At the moment we do `glow::optimize` before gathering profile and quantizing the model. Since it's not backend-specific, we end up with the same graph for every backend, so it's possible to gather quantization profile with one backend and run quantized model with another.
I think it'd be good to keep this property, as it makes sense that some backends may support only quantized models. In fact, last time I checked (a while ago) profile generation was not possible with CPU backend, only with Interpreter.
