### ISSUE TITLE
[GraphOptimizer] Optimizations clobber graph with dead nodes

### ISSUE THREAD

**Issue by aturetsk** [pytorch/glow#1688]
Optimizations in GLOW do not erase transformed nodes from the graph and relay on DCE to clean up. This corrupts number of node users (e.g. an optimization can't relay on node->hasOneUser() unless DCE has been done right before it).

It looks like GLOW optimizations are going to be refactored into separate classes inherited from FunctionPass (https://github.com/pytorch/glow/pull/1659). In this case one of the possible solutions is to make FunctionPass class always call DCE after the optimization is done.

**Comment by jackm321** [comment]
This can be closed right?

**Comment by aturetsk** [comment]
@jackm321, I don't think this has been fixed. Optimizations keep replacing node uses with newly created nodes w/o removing old nodes.

**Comment by bertmaher** [comment]
This issue is pretty interesting.  I don't think it's correct to say that RAUW "corrupts" the graph, because the graph is still valid after RAUW, it just contains obvious dead code (i.e. the thing that was replaced) that might prevent other optimizations from kicking in.

1. We could try to make RAUW erase the replaced node from the graph.  But this approach is very dangerous, because you're usually calling RAUW inside a loop over the nodes, and erasing from a list while iterating it can easily lead to dereferencing freed things.  (I have taken this approach in other systems, though.)
2. We could iterate optimizations followed by DCE to a fixed point (similar to what's suggested in the initial issue report).  This approach is pretty common, although we have to be careful not to accidentally create some quadratic-or-worse behavior.

**Comment by nickgg** [comment]
@bertmaher is this still an issue?

**Comment by rdzhabarov** [comment]
I think this can be closed. We have DCE() runs after bunch of optimizations now (not all though).
