### ISSUE TITLE
[New operator] FCTransposed

### ISSUE THREAD

**Issue by artemrakhov** [pytorch/glow#1697]
We need to support `FCTransposed` operator from Caffe2. Spec can be found here:
https://caffe2.ai/docs/operators-catalogue.html#fctransposed

**Comment by qcolombet** [comment]
Just to double check. When we say new operator that means adding this operator in the loader, not necessarily adding a new glow node, right?
In particular for this case, the loader would have to emit (FC input, (transpose W)).

I think adding this kind of details for the various issues you've added (thanks BTW) would help potential contributors to jump in. Otherwise we may scare them away :).

**Comment by artemrakhov** [comment]
Yes, for this operator, one needs to change only `Caffe2.cpp` and add test.
No need to have `createFCTransposed` in the Graph class.
Create transpose for weights, create regular FC. Perhaps reuse existing code for `FC` to avoid duplication:
https://github.com/pytorch/glow/blob/72c28e22e31091db455c1cec5fbcf734a615c646/lib/Importer/Caffe2.cpp#L296

**Comment by rdzhabarov** [comment]
Going to add this operator for ONNX/ONNXIFI support.

**Comment by rdzhabarov** [comment]
closing this as the change was merged.
