### ISSUE TITLE
Remove all executable tests from the Caffe2 and ONNX loaders

### ISSUE THREAD

**Issue by nadavrot** [pytorch/glow#1801]
The role of the Caffe2 and ONNX loaders is to load the protobuf from a protobuf file into the Glow graph. The loader unit tests need to check that the complex operators are loaded into the graph nodes properly and that the correct graph is constructed. The *operator* unit tests need to verify that the low-level operators are executed correctly. 

Some of the loaders create a complex structure of nodes, but this design is not ideal for a number of reasons.  First, the same structure has to be duplicated between the ONNX and Caffe2 loaders, or shared by means of inheritance. Second, the unit tests that check the loader become complex and slow. A better design would be to use the graph builder to generate the non trivial nodes.

To demonstrate this PR let's look at the transposed-matmul node. The loader needs to construct the two nodes: transpose + matmul. These nodes are already tested independently in the operator unit test. A clean implementation and unit test would be to add a graph builder that creates the new construct, that looks like createTransposedMatmul(). We could write an operator test for the createTransposedMatmul method, if we feel like it is complex enough to be worth a unit test. The c2/onnx loader just needs to call createTransposedMatmul, and the unit test just needs to verify that the two nodes are created. The Loader unit test should not execute any networks, they are unit tests, not system tests. 

In this task you will need to go over the caffe2 unit tests and identify the new operators. Refactor each new complex operator inside the loader into the 'createXXX' method, and move the execution part of the unit test into a new test in the operator test unit test.

**Comment by nadavrot** [comment]
@beicy @artemrakhov

**Comment by artemrakhov** [comment]
> First, the same structure has to be duplicated between the ONNX and Caffe2 loaders, or shared by means of inheritance.

Could you please clarify more on this? Why is it bad to share common complicated logic by inheritance? Do you propose to have a separate builder (not related to Function and Caffe2ModelLoader classes), or add createXXXX methods to Function class?

I feel that a lot of this complex code in loaders is really tied to either Caffe2 or ONNX specifics. And also tied to processing a proto and retrieving fields from it. Please look at matrix multiplication code pieces for example. We have:

1. MatMul in Caffe2
1. MatMul in ONNX
1. FC and FCTransposed in Caffe2
1. Gemm in ONNX.

If we moved these 4 code pieces to Function class (under corresponding createXX names), the class would become overpopulated, with many methods doing essentially the same thing.

I agree that current flat structure with big function (method) and a lot of ifs is not ideal. Maybe we should split it into separate methods within the same class (Caffe2ModelLoader)? That way, restructured unit test could call each method individually.

Creating a new separate GraphBuilder (FunctionBuilder?) is also a way to proceed, but it feels to me as one extra level of abstraction. Because there will be Caffe2GraphBuilder and ONNXGraphBuilder, sharing some parts, and working with protobuf just like existing Loaders.

**Comment by nadavrot** [comment]
> I feel that a lot of this complex code in loaders is really tied to either Caffe2 or ONNX specifics.

I see your point. Adding a bunch of createXXX methods would complicate the graph builder with all of the details of all of the loaders. Yes, you are right. 

I was hoping to split the loader unit tests into two parts: operator test and loader test. Can you think of a way to reduce the complexity in the current scheme?

**Comment by artemrakhov** [comment]
First, we can all agree not to test execution functionality in loader tests. If anything, just move such tests to operator tests and use C++ API to create graph there.

Then split out separate methods from Caffe2ModelLoader's big method. Then they can be tested individually. What do you think? We'll still leave at least one complete test to make sure that Caffe2ModelLoader is able to run end to end.

**Comment by nadavrot** [comment]
I am not sure how we can construct the exact same graph structure in the operator test and in the Caffe2Loader test, without duplicating the code. At first I thought that createXXX functions could help us, but now I agree with you that this would complicate the graph builder.
