### ISSUE TITLE
Build tools for "cosimulation" of networks

### ISSUE THREAD

**Issue by bertmaher** [pytorch/glow#1976]
This task is mostly for my own benefit ;-)

I've found it pretty useful to check intermediate results of networks against various backends to understand where things might be going off the rails.  There are a few things that I've built in a hacky local branch that I want to land in the main repo:
- A utility for converting png format images to raw binary Tensors.
- A utility for dumping Tensors to raw binary files and reading them back in from same.
- A utility function to cut a Graph at an arbitrary named Node, so as to easily read out the value at that point.
- (Something I haven't built) The ability to replace a named node with an input Variable.

Taken together these would allow you to very easily write verification scripts that slice up a network, run on different backends, and compare the results.  Conceptually they're similar to DebugPrint instrumentation, except "print" can be a tricky concept for ASICs/FPGAs/emulators depending on where each project is in its bring-up stage.

**Comment by opti-mix** [comment]
Looking forward to see this functionality in action!

Two comments/suggestions:

> A utility for dumping Tensors to raw binary files and reading them back in from same.

We probably need to take care that these tensors are always written using the same byte-order, i.e. little-endian or big-endian, so that they can be read across different processors/HW accelerators.

> A utility function to cut a Graph at an arbitrary named Node, so as to easily read out the value at that point.

It could be also useful to be able to cut a Graph at an arbitrary kind of node (e.g. at any Conv node), so as to easily read out the value at that point.

**Comment by bertmaher** [comment]
>  take care that these tensors are always written using the same byte-order

Just as you wrote this I was writing a comment about how the I/O functions I've created don't handle endianness.  */me looks sheepish*
