### ISSUE TITLE
Support enum members on nodes

### ISSUE THREAD

**Issue by stoklund** [pytorch/glow#2053]
Currently, nodes defined by ClassGen can only have members that are scalars or vectors of scalars. When defining backend-specific nodes, it would be really helpful if we could add node members with `enum` type. At the moment, we do this by adding an `MemberType::Unsigned` member and casting to and from the real `enum` type. This is inviting type errors.

I suggest an interface like this:

```c++
auto frob = BB.newEnum("mybackend::Frob");

BB.newNode("MyPool")
    .addInput("Input")
    .addMember(frob, "FrobA")
    .addMember(frob, "FrobB")
    .addMember(MemberType::VectorUnsigned, "Kernels")
```

The `Builder::newEnum()` method should take enough arguments for ClassGen to generate a correct forward decl for the `enum class` type.

**Comment by nadavrot** [comment]
We had this feature in ClassGen but we removed it last year. We had an arithmetic node that had an enum that specified if the node was Add, Sub, Mul, etc. It could be useful to search git log for the implementation.

**Comment by jfix71** [comment]
@nadavrot We still have it ([see here](https://github.com/pytorch/glow/blob/master/tools/ClassGen/NodeBuilder.h#L102)), though it's currently unused. I believe it's only useful for adding a single enum with many different cases to a single node, e.g. as you mentioned for an Arithmetic node with Add, Sub, etc. modes, where those modes are enumerated in the node definition.

What @stoklund is suggesting uses enums that are externally defined. Then these enums can be reused across different nodes, and don't need to be enumerated on every node that uses them. Nodes could also have multiple enums.

**Comment by stoklund** [comment]
> Then these enums can be reused across different nodes, and don't need to be enumerated on every node that uses them. Nodes could also have multiple enums.

I'm pretty sure we would need both of these features.

**Comment by SplitInfinity** [comment]
I posted a WIP pull request for this. I have a few questions:
- do we have tests for `ClassGen`?
- do we need to support custom values? e.g.
```
enum class MyEnum {
   FIRST = 5,
   SECOND = 21,
}
```
- do we need to support customization of the underlying type of the enum? e.g.
```
enum class MyEnum: unsigned {
  ...
}
```

**Comment by opti-mix** [comment]
> do we need to support custom values? e.g.

I'm pretty sure this would be useful.

> do we need to support customization of the underlying type of the enum?

I'd say it is nice to have, but not strictly needed.

**Comment by opti-mix** [comment]
I also commented on your PR about some further features. Here is a copy of my comment:

I've got a couple of requests.

The easy ones:

- Could you allow for setting doc-strings for enumerators as well?
    May be using an API like addCase(std::string enumeratorName, std::string enumeratorDoc = ""), so that the doc-string is optional.

- Could you allow for specifying a numeric value for the enumerators?
    May be using an API like addCaseWithValue(std::string enumeratorName, int enumeratorValue) or something like this?

The more complex ones:

- Regarding using the enums declared externally: you say that they need to be forward declared. Does it need to be done using NodeGen APIs? Or do you need to write (or include) a usual C++ forward declaration? Do you need to/Can you include any backend-specific header files defining the actual type? Can your approach be used only for enums or could it be extended to support any other externally defined types? It could be very useful to be able to use externally defined types as types of the members.

- We may need to add the same features to the InstrGen, because e.g. when we lower a node into a backend-specific instruction, we most likely want to propagate the members of custom types into this instruction.

**Comment by SplitInfinity** [comment]
I've updated the pull request to allow docstrings on individual enumerators and to allow specification of the numeric value attached to an enumerator. As for your more complex questions:

**Does [forward declaration] need to be done using `NodeGen` APIs? Or do you need to write (or include) a usual C++ forward declaration?**

`NodeGen` automatically generates forward declarations for any enum added using the `NodeGen` API. You do not need to write or include these yourself. Perhaps these APIs are not named in the best way, but `Builder::addEnum` will generate both the necessary forward declarations  and definitions, and `Builder::addBackendSpecificEnum` will generate only the forward declarations. In the latter case, it is assumed that the enum is defined in the correct namespace elsewhere.

**Do you need to/Can you include any backend-specific header files defining the actual type?**

You can but you don't need to. As long as the auto-generated files are compiled and linked against a translation unit that has the definitions, it should work.

**Can your approach be used only for enums or could it be extended to support any other externally defined types?**

I gave this some thought and I don't think this can be extended to support any other externally defined types because `NodeGen` generates equator, cloner and hasher functions for every `Node`, and adding code to these functions for the arbitrary externally defined types requires knowledge of their interface. But with a forward declared type, you can only use pointers and references to it without dereferencing them. The reason I think it works out for enums is because their underlying type is always known. 

It might be possible to get around this by providing the ability to include a backend-specific file in the autogenerated `.cpp`. Then, the full interface will be available and the equator, cloner and hasher functions can be properly generated.
