### ISSUE TITLE
[Bug] Overflow in FunctionSpecializer

### ISSUE THREAD

**Issue by yinghai** [pytorch/glow#2059]
I encountered this piece of code:
https://github.com/pytorch/glow/blob/fc98cd34b8e7374e4494ef0db82623725b86b826/lib/Backends/CPU/FunctionSpecializer.cpp#L362-L364

This is not safe as the number of operands of the function (`e`) can exceed `63` and this will induce overflow/undefined behavior at
https://github.com/pytorch/glow/blob/fc98cd34b8e7374e4494ef0db82623725b86b826/lib/Backends/CPU/FunctionSpecializer.cpp#L83

I actually did read the code enough to understand what functions in this file do but this doesn't look right.

**Comment by yinghai** [comment]
I wonder if we can just truncate and use the first 64 arguments by replace
https://github.com/pytorch/glow/blob/fc98cd34b8e7374e4494ef0db82623725b86b826/lib/Backends/CPU/FunctionSpecializer.cpp#L81
with 
```
return (argIdx > 63) ? false : argsToBeSpecialized & (((uint64_t)1) << argIdx);
```

**Comment by yinghai** [comment]
@bertmaher @opti-mix

**Comment by opti-mix** [comment]
@yinghai Good catch! I agree that this will induce overflow/undefined if the number of operands of the function would exceed 63. 

But I don't think it is very likely that we ever get a function with >63 operands. Thus, as a simplest solution I'd suggest adding an `assert` checking that the number of operands is <=63. 

A more future proof solution would be to use e.g. a dynamic `bitset` (or any other data structure which can have a dynamically defined size) instead of a fixed-width 64bit unsigned value to hold the mask.

**Comment by opti-mix** [comment]
> return (argIdx > 63) ? false : argsToBeSpecialized & (((uint64_t)1) << argIdx);

Yes, seems like this could work. And as I described above, it is very unlikely that we ever hit the case `argIdx > 63`.

**Comment by yinghai** [comment]
> Yes, seems like this could work. And as I described above, it is very unlikely that we ever hit the case argIdx > 63.

It's very likely when we have a lot of parallel embedding looks as inputs. :)

**Comment by opti-mix** [comment]
> It's very likely when we have a lot of parallel embedding looks as inputs. :)

You mean we would pass those inputs not as a tensors of size > 63, but as separate arguments of a function? Hmm. I haven't thought about this use-case ;-)

BTW, does it even make sense to specialize for embedding table look-ups? Because if we don't expect any speed-ups from the specialization, there is probably no reason to specialize in these cases. It will just bloat the code size.

**Comment by yinghai** [comment]
> does it even make sense to specialize for embedding table look-ups? 

I don't think it makes sense for now. But it goes into this code path anyway and I have no idea why. :) This is flushed out by the real case BTW.

**Comment by opti-mix** [comment]
The actual reason for having LLVM functions with so many arguments turned out to be due the auto-generation of stacked kernels by `emitDataParallelKernel`. This function introduces a new function argument for each unique buffer used by the kernel. And apparently there are some use-cases with more than 64 unique buffers being used by a single kernel. 

Since such situations are pretty rare and most likely having huge auto-generated kernels for such cases does not make a lot of sense, we could just limit the number of unique buffers that can be used by any given kernel to 64.
