### ISSUE TITLE
Quantizing after lowering causes issues with FullyConnected

### ISSUE THREAD

**Issue by tlepley-cadence** [pytorch/glow#2395]
@jfix71 there are some side effects to your changes in #2311.  Some operations have specific quantized types. This is for instance the case for FullyConnected that has its bias param quantized as Int32QTy.

The problem is that this FullyConnected nodes gets lowered as MatMul and BatchAdd. Since the actual IR quantization now happens after Lowering,  the bias is now quantized as Int8QTy with BatchAdd, not anymore as Int32QTy.

I causes some issues with our backend.

**Comment by jfix71** [comment]
@tlepley-cadence Thanks for raising this issue!

It seems the `FunctionQuantizer` needs to know each nodes' origin node that it was lowered from. After talking with @rdzhabarov, we think the best solution for now is to extend the `LoweredNamesMap` to include the origin node's `NodeKind` instead of just its output name. This way the `FunctionQuantizer` can check if e.g. a `BatchedAddNode` was lowered from a `FullyConnectedNode` in order to handle it correctly and use `Int32QTy` for the bias.

In the long run it may make sense to change the `LoweredNamesMap` to instead map between `NodeValues` instead of `string` -> `string` + `NodeKind`. This could be useful for other purposes, e.g. debugging to track where nodes came from, or to use during performance profiling. However one downside here is that the `NodeValue` includes a pointer to a `Node`, but the `Node` would already have been deleted by DCE by the time it's dereferenced. So we would need to modify DCE in this case to remove the node from the Function, but still keep it around in memory until it's no longer needed.
