### ISSUE TITLE
How operator stacking is implemented?

### ISSUE THREAD

**Issue by zhangfanghn** [pytorch/glow#2409]
In cpu backend，as mentioned in the [paper](https://arxiv.org/pdf/1805.00907.pdf) 5.2(operator stacking),  I am confused,  how operator stacking is implemented?  Is there an example to explain it？

**Comment by jfix71** [comment]
Hi @zhangfanghn -- essentially the Instruction definition found in [InstrGen](https://github.com/pytorch/glow/blob/master/tools/ClassGen/InstrGen.cpp) should include `.dataParallel()`, so that the instruction is known to be data parallel. For example for elementwise max:

https://github.com/pytorch/glow/blob/0f4139092cf34b22b1c46fc0c2c3466daf22dd0a/tools/ClassGen/InstrGen.cpp#L355-L362

Then during LLVM IR generation, when we encounter such a data parallel operation, we emit IR to stack (vertically fuse) them into a single "bundle" which execute in a single pass of the data automatically, inside `LLVMIRGen::generateLLVMIRForModule()`:

https://github.com/pytorch/glow/blob/eaf135b178dcde443101b626f84ae6c843089445/lib/Backends/CPU/LLVMIRGen.cpp#L807-L817

Lastly we define such data parallel instruction kernels in `libjit` very simply, like so for elementwise max:

https://github.com/pytorch/glow/blob/eaf135b178dcde443101b626f84ae6c843089445/lib/Backends/CPU/libjit/libjit.cpp#L710-L713

**Comment by opti-mix** [comment]
@jfix71 Thanks for a prompt reply! You were faster than me ;-)

**Comment by zhangfanghn** [comment]
@jfix71 I got it. Thank you !
