### ISSUE TITLE
[DeviceManager] Enforce correct type of CompiledFunction for addNetwork

### ISSUE THREAD

**Issue by jfix71** [pytorch/glow#2410]
While creating https://github.com/pytorch/glow/pull/2398, I realized that it seems the test currently is creating a `CPUDeviceManager`, but then calling `addNetwork()` on it with a `InterpreterFunction`. This seems like it shouldn't be possible or at least should fail somehow.

@rdzhabarov also mentioned that if all device managers are expected to have `maxMemoryBytes_` supplied as part of the init then perhaps we should extend the `createDeviceManager()` call with it. If we do expect all device managers to have it then it should probably also be moved to `DeviceManager`?

CC: @nickgg

**Comment by nickgg** [comment]
Yes, that makes sense to me, I'll take care of it.

Re the second question, i think each DeviceManager could need slightly different construction parameters depending on the specifics of the hardware (e.g. device path? socket?) and we'll need some way to pass arbitrary info to the creation factory. Rather than pass in a fixed max size it would be better if the DeviceManager queried the physical hardware for it's max/available space on startup. Sorry no good answers here, was hoping the right approach would make itself known as we spent more time with the devices.
