### ISSUE TITLE
ONNXImporterTest importPad tests expected results?

### ISSUE THREAD

**Issue by vuzelac-cadence** [pytorch/glow#2432]
I am looking into importPadEdge testCase, and it throws message "only the 'constant' mode is currrently supported".  From there, we have different behavior in Linux and Windows.
In Linux, the test passes which looks correct, however, in Windows it results in Unhandled Error and abort (`Error::fatalUncheckedError()` function in LLVM `Error.h`).
Want to check if you have tests tried and running with LLVM's `LLVM_ABI_BREAKING_CHECKS` enabled ?

**Comment by jackm321** [comment]
Hi @vuzelac-cadence, I think the error that is reported as unchecked would be this one
https://github.com/pytorch/glow/blob/60b21bc6adb5444c079ac63899fcd037a57768dc/tests/unittests/OnnxImporterTest.cpp#L967-L969
I don't think we've run tests with `LLVM_ABI_BREAKING_CHECKS` so this is something that we should verify.
I would think that with `LLVM_ABI_BREAKING_CHECKS` enabled, this shouldn't be an issue though because the llvm::Error is checked on line 969 over the above code so I'll have to see why this would be failing.
