### ISSUE TITLE
[GraphOptimizer] Shouldn't there be an option to disable specific graph optimizations that are happening?

### ISSUE THREAD

**Issue by suyash-cadence** [pytorch/glow#2591]
I am looking at the _optimize()_ function and came across _optimizePool()_. I would like to have an option to disable this optimization. Is it a good Idea to add an command line option to disable this optimization?

**Comment by jfix71** [comment]
I think disabling optimizations via the command line isn't a direction we want to go -- e.g. it's not scalable at all, since other optimizations may want to be disabled too. Ideally it's something the backend would control through some mechanism -- this is related to https://github.com/pytorch/glow/issues/1641. I'd love for someone to take a swing at that issue if you're up for it.

**Comment by suyash-cadence** [comment]
To avoid duplicate issues, I am closing this issue as it appears to be a very much related/same to #1641.
