### ISSUE TITLE
LSTM operator is not supported

### ISSUE THREAD

**Issue by ajayanto** [pytorch/glow#3475]
When I try to compile the following model,

![image](https://user-images.githubusercontent.com/16913915/63993203-02976380-cb0d-11e9-9979-fbab44293ecf.png)

 I got the following error 
MODEL_LOADER_UNSUPPORTED_OPERATOR message: Failed to load operator LSTM

It seems LSTM operator is not implemented in glow.

**Comment by jfix71** [comment]
Hi @ajayanto, thanks for opening the issue. We do not currently support loading the LSTM, but we do support all of its components. We haven't made a lot of progress here because LSTMs are usually used in RNNs, and Glow does not currently support control flow which is needed for RNNs. The best option for RNNs right now is to unroll them to some max length, but that isn't currently supported directly in Glow -- it must be done loading the model into Glow.

So, if your model is not an RNN model/it doesn't need control flow, then this should be something that can fixed without a lot of work. Do you have any interest in working on this?

**Comment by ajayanto** [comment]
We are looking into an RNN model. Is there any guidance available for RNN control flow implementation in glow?

**Comment by jfix71** [comment]
See the previous discussion in #2738. Going to close this issue as a duplicate, please continue the discussion there.
