### ISSUE TITLE
Compiling Habana backend missing   SYNAPSE_INCLUDE_DIR

### ISSUE THREAD

**Issue by vnaveen0** [pytorch/glow#3543]
I tried compiling: 

    cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DGLOW_WITH_HABANA=ON  -DGLOW_WITH_BUNDLES=ON -DGLOW_WITH_CPU=ON ../

But the following directories are missing in the repository : 

    glow/tests/unittests/SYNAPSE_INCLUDE_DIR
    glow/lib/Backends/Habana/SYNAPSE_INCLUDE_DIR

**Comment by BrotherTen** [comment]
I also encountered the same problem. 
`
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files: /home/zjh/workspace/glow/lib/Backends/Habana/SYNAPSE_INCLUDE_DIR
    used as include directory in directory /home/zjh/workspace/glow/lib/Backends/Habana
/home/zjh/workspace/glow/tests/unittests/SYNAPSE_INCLUDE_DIR 
    used as include directory in directory /home/zjh/workspace/glow/tests/unittests
`
I checked the file **CMakeList.txt** and find that:
` 
list(APPEND CMAKE_PREFIX_PATH /usr/lib/habanalabs)
find_path(SYNAPSE_INCLUDE_DIR synapse.h)  
find_library(SYNAPSE_LIB Synapse) 
find_library(TPCSIM_SHARED_LIB tpcsim_shared)
find_library(HL_THUNK_LIB hl-thunk)
`
It seems that there should be a directory **habanalabs** in my local **/usr/lib**. Is it because I have some libraries that are not installed?

**Comment by niniack** [comment]
Having this same issue. Damn shame too, I was quite excited to run with the Habana backend. 

`CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
/home/usr/coa_final/glow/lib/Backends/Habana/SYNAPSE_INCLUDE_DIR
   used as include directory in directory /home/usr/coa_final/glow/lib/Backends/Habana
/home/usr/coa_final/glow/tests/unittests/SYNAPSE_INCLUDE_DIR
   used as include directory in directory /home/usr/coa_final/glow/tests/unittests`

**Comment by bertmaher** [comment]
Do you have Habana's synapse library installed?

**Comment by niniack** [comment]
I suppose not, could you point to me in the right direction? Didn't come across documentation regarding it! Thank you

**Comment by ybai62868** [comment]
Hello,

I get the following error messages when I compile the habana backend:

-- Found PythonInterp: /root/miniconda3/bin/python (found version "3.7.4")
Skipping adding test en2gr_cpu_test because it requires a models directory. Configure with -DGLOW_MODELS_DIR.
Skipping adding test en2gr_quantization_test because it requires a models directory. Configure with -DGLOW_MODELS_DIR.
Skipping adding test en2gr_cpu_partition_test because it requires a models directory. Configure with -DGLOW_MODELS_DIR.
Skipping adding test en2gr_cpu_config_test because it requires a models directory. Configure with -DGLOW_MODELS_DIR.
Skipping adding test resnet_runtime_test because it requires a models directory. Configure with -DGLOW_MODELS_DIR.
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
/root/glow_2/glow/lib/Backends/Habana/SYNAPSE_INCLUDE_DIR
   used as include directory in directory /root/glow_2/glow/lib/Backends/Habana
/root/glow_2/glow/tests/unittests/SYNAPSE_INCLUDE_DIR
   used as include directory in directory /root/glow_2/glow/tests/unittests

-- Configuring incomplete, errors occurred!
See also "/root/glow_2/glow/build/CMakeFiles/CMakeOutput.log".
See also "/root/glow_2/glow/build/CMakeFiles/CMakeError.log".

Does anyone know how to solve it?

**Comment by bertmaher** [comment]
CMake expects to find Habana's libraries installed in /usr/lib/habanalabs (https://github.com/pytorch/glow/blob/eeceb9adda005635b2228f143e0d848c2fd19339/CMakeLists.txt#L128) or otherwise locate it via CMAKE_PREFIX_PATH. 
 You probably don't have Habana's SDK installed.

Also, a general comment/question for anyone encountering this problem: do you actually have a Habana card installed in your machine?  If not, you can't use the Habana backend -- it's designed to work with an ASIC accelerator

If you *do* have a Habana card installed, then we can have a fruitful discussion about how to build Glow in your environment.

**Comment by psyhtest** [comment]
It's a shame. I was quite interested to give the backend a spin ahead of getting a Habana card...
