### ISSUE TITLE
regression: model-runner: gemmlowp quantization flow broken

### ISSUE THREAD

**Issue by Verma-Rajat** [pytorch/glow#4188]
After integration of below commit:

commit 855775629b8be67116012770bc044e90b23646e7
Author: Iancu Ciprian Mindru <mciprian13@yahoo.com>
Date:   Fri Jan 24 16:46:13 2020 -0800

    Enable constant folding by default and extra fix. (#4027)

GEMMLOWP flow is broken for caffe2 models, when executed through model-runner.

For attached single node Add operator graph, gemmlowp output is incorrect (exactly same for FP32 and Gemmlowp, which was not the case before).

**Dump quantization profile:**
model-runner -m predict_net.pb -m init_net.pb -backend Interpreter -dump-profile=ICEREF_GEMMLOWP_PROFILE.yaml -quantization-precision=Int8 -quantization-schema=asymmetric
**Execute quantized flow**
model-runner -m predict_net.pb -m init_net.pb -backend Interpreter -load-profile=ICEREF_GEMMLOWP_PROFILE.yaml
**max: 1.975  min: -1.941**

Before this commit, output was:
**max: 1.981  min: -1.935**

**Comment by jfix71** [comment]
@Verma-Rajat Thanks for reporting this! I'm not sure this is actually "incorrect" or broken, though, depending on your definition of broken 🙂-- do you have some reason why you believe the results before this were "more" correct?

I am assuming what happened is that after that PR, some set of constant ops are now executed one by one, whereas before that PR it was constant folded in the optimization pipeline, which means that some graph optimizations may have changed the graph before constant folding. Also constant folding in the optimization pipeline constant folds multiple ops at a time instead of one at a time, which could slightly changed the numerics.

BTW, if you prefer the old numerics you could always use `-const-fold-ops=false`.

CC: @mciprian13

**Comment by Verma-Rajat** [comment]
After merge of that PR, below command was producing graphs that didn't had dequantize nodes at all, and graph was executing in FP32. (see gemmlowp_with_const_fold_ops_as_true.png).
model-runner -m predict_net.pb -m init_net.pb -backend Interpreter -load-profile=ICEREF_GEMMLOWP_PROFILE.yaml

However, if I use -const-fold-ops=false, I get a graph with dequantize nodes and graph executing in gemmlowp as expected (gemmlowp_with_const_fold_op_as_false.png). 

So, it solves my problem. thanks.
![gemmlowp_with_const_fold_op_as_false](https://user-images.githubusercontent.com/46986892/74704591-f330e180-5236-11ea-8400-1bdf3704c7aa.png)
![gemmlowp_with_const_fold_ops_as_true](https://user-images.githubusercontent.com/46986892/74704594-f4faa500-5236-11ea-9ad3-490c6f473c17.png)

**Comment by jfix71** [comment]
@Verma-Rajat Glad this helped. I'm actually not sure why quantization would have made any difference here -- curious at what point you dumped the second DAG here. Based on the compilation pipeline, constant folding should have kicked in before quantization, so I'm not really sure how you got the second DAG.

**Comment by Verma-Rajat** [comment]
second DAG was produced with below command:
model-runner -m predict_net.pb -m init_net.pb -backend Interpreter -load-profile=ICEREF_GEMMLOWP_PROFILE.yaml -dump-graph-DAG=graph.dot -const-fold-ops=false
