### ISSUE TITLE
Pytorch Source for  resnet18.pt binary model in Glow torch_glow 

### ISSUE THREAD

**Issue by dinkdeep** [pytorch/glow#4268]
1. The torch_glow seems to have a pytorch model possibly built using JIT script, Glow seems to train this model  tests/models/pytorchModels/resnet18.pt. Where can I get the original soruce code  Pytorch model written for it in Python, The idea would be to get the original python code and trim it may be reduce/add some nodes and regenerate the .pt model it and experiment with it. 

2. Or is there a way where the pt model can be converted to a txt model like pttxt something on the lines of ONNX where a .ONNX binary model can be converted to a ONNXTXT text model and correspondingly this text file can be  manipulated with hand by adding/deleting nodes and can be efficiently hand  crafted .

3. Or this there a tool/method to get the visibility the pt file and further ability to tweak it .

**Comment by dinkdeep** [comment]
Hi, Jack/Jordan Can you guys kindly provide me with the link to python source code from which resnet18.pt was generated this file seems to ship with glow in folder tests/models/pytorchModels/ and probably uses the Torch jit call torch.jit.trace, @torch.jit.script_method and torch.jit.save calls , 
I believe you guys might have compiled it through source and checked-in.

**Comment by jackm321** [comment]
Hi @dinkdeep 
1. The original model is from torchvision https://pytorch.org/docs/stable/torchvision/models.html#classification. The source for it can be found here https://github.com/pytorch/vision/blob/master/torchvision/models/resnet.py#L226. You may also be able to use the `setFusionBlacklist` flag in torch_glow to keep some op kinds in PyTorch instead of fusing them to glow. An example of using this would be something like --setFusionBlacklist="quantized::linear"

2. Not that I'm aware of unfortunately. Models in PyTorch are not serialized to a protobuf similar to onnx

**Comment by dinkdeep** [comment]
Thanks Jack, I will give it a shot, In the meanwhile I was able to get hold of a similar model from nv site https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/Classification/ConvNets/image_classification/resnet.py and able to generate the pt file and tinker it .
