### ISSUE TITLE
[GraphOptz] Specialize 1x1 Convolutions to FullyConnected

### ISSUE THREAD

**Issue by mciprian13** [pytorch/glow#4463]
I think it is reasonable to expect that a 1x1 Convolution (with pads all 0's) which is mathematically equivalent to a FullyConnected can be processed faster by a FullyConnected kernel than a Convolution kernel regardless of the Backend. Here is an example from a MobileNet model which has chained 1x1 Convolutions:
![image](https://user-images.githubusercontent.com/29785908/80356693-7c414600-8882-11ea-9a91-ad735eb379ad.png)
I think this specialization should be done and made part of the GraphOptimization pipeline.
If you agree (give me green light) I would like to do this. All I need is a hint of where this pass should be implemented (cuz there are multiple pipelines and I am not that familiar with all of them).
Thanks!

**Comment by aturetsk** [comment]
The problem I see with this is that converting 1x1 Conv into FC early in the compilation flow will prevent some optimizations from happening. Or implementation of each applicable transformation will have to be extended to cover both FC and Conv, which is a bit messy. Arguably, but for this exact reason on graph level it might make more sense to do the opposite (convert FC to 1x1 Conv so that all graph transformations would be implemented just for Conv)... Maybe doing 1x1 Conv node -> FC instruction lowering during IRGen would be less disturbing?

**Comment by jfix71** [comment]
IMO this fits reasonably into the folding/lowering passes we have, since we do `optimize -> fold -> optimize -> lower`. So first we'd hit optimizations for FC, then we'd fold to 1x1 Conv, hit optimizations for Conv, then lower back to FC. Note that the lowering part here could be implemented without the folding part as intended in the original post. Any concerns or places you see an issue with this approach? @aturetsk

**Comment by aturetsk** [comment]
No, I don't think there are any concerns if done in `lower` stage (after all, this part is controlled by backend, thus the transformation can be disabled by a backend if so desired).

**Comment by mciprian13** [comment]
@jfix So I'm not sure I understand where exactly is the right place to do this specialization. My intention is to have this specialization by default part of the CPU backend which is the backend I currently use.

**Comment by jfix** [comment]
Hi, just to say you probably want to talk to @jfix71 ... 😉

**Comment by jfix71** [comment]
@mciprian13 You'd add a case for `Conv1x1 -> FC` to `glow::lowerNode()` in `Optimizer/Lower/Lower.cpp`. And if you were interested in the other direction too, you'd add a pass for `FC -> Conv1x1` and add it to `createDefaultFoldPassPipeline()`.

**Comment by mciprian13** [comment]
@jfix71 Got it. One question though: is the lowering procedure recursive? Meaning that after the 1x1Conv is lower to FC, will the FC get automatically lowered again to MatMul + BatchAdd for the CPU Backend?

**Comment by jfix71** [comment]
>after the 1x1Conv is lower to FC, will the FC get automatically lowered again to MatMul + BatchAdd for the CPU Backend?

@mciprian13 Yeah it would be lowered, but only if the backend returns true for `shouldLower()`.

**Comment by mciprian13** [comment]
@jfix71 Ok thanks!

**Comment by mciprian13** [comment]
Solved in #4615. Closing this issue.
