### ISSUE TITLE
[Node] The Node::clone() function has memory leaks.

### ISSUE THREAD

**Issue by mciprian13** [pytorch/glow#4470]
When using the `Node::clone()` function for a Convolution node for example the ASAN complains about a memory leak regarding the unsigned_t vectors **Kernels**, **Strides** and **Pads**. I think this has to do with the conversion made from llvm::ArrayRef to std::vector but I'm not sure because I don't really understand the llvm::ArrayRef type.

Similar thing happens if I generate and use the setters for those vector fields using the option
`/* addSetter */ true` in `NodeGen.cpp`.

Here is a log from the MemorySanitizer:
[NodeCloneMemoryLeak.txt](https://github.com/pytorch/glow/files/4551838/NodeCloneMemoryLeak.txt)

**Comment by mciprian13** [comment]
@opti-mix @jfix71 Do you know why this happens?

**Comment by jfix71** [comment]
Hm, no I'm not sure. We have a test for this where we create a `ConvolutionNode` and clone it (see `cloneTest` in `GraphTest`), and it's run in CI with ASAN. The log you posted is showing where the memory is allocated, not leaked, right? So perhaps the cloned node is leaked somewhere in the node splitting PR as that appears to be where the issue is seen?

**Comment by mciprian13** [comment]
@jfix71 In my node splitting function I first run a round of searching of a split configuration and I create some temporary clones. I explicitly verified that the temporary clones are destroyed. If you look at the log the memory leak refers to the Kernels, Strides and Pads fields of the convolution clone (16 byte, 8 byte and 8 byte per object). How could this be?

**Comment by opti-mix** [comment]
> I think this has to do with the conversion made from llvm::ArrayRef to std::vector but I'm not sure because I don't really understand the llvm::ArrayRef type.

ArrayRef does not allocate any memory. It is basically a pointer to the beginning of the memory of a previously allocated array (e.g. C array or std::vector) and the number of elements in it.

**Comment by jfix71** [comment]
>If you look at the log the memory leak refers to the Kernels, Strides and Pads fields of the convolution clone (16 byte, 8 byte and 8 byte per object). How could this be?

@mciprian13 Assuming the ConvolutionNode is getting destructed then it doesn't make any sense -- these are `std::vectors` and so they would always be destructed when the ConvolutionNode is since they're members of it. This shouldn't have anything to do with `ArrayRef` -- as @opti-mix mentioned it's just a wrapper around other memory, and when we call the ConvolutionNode constructor it just copies the data from the `ArrayRefs` into the `std::vectors`.

This is why I am thinking it's an issue with a ConvolutionNode not being destructed. Can you try running with a debugger to see if you can figure out the name or ptr of the ConvolutionNodes that are leaking, and then track down where they're allocated from and their lifetime/when you think they're being destructed?

**Comment by mciprian13** [comment]
@jfix71 You were right. I was not deconstructing correctly the temporary nodes. Initially I used a `std::vector<unique_ptr>` for the clones but this only called the destructor from the base class `~Node()`. Instead I used now the function `Node::destroyNode()` which I made public in `Node` class.
Thanks!
