### ISSUE TITLE
[Quantization] Questions

### ISSUE THREAD

**Issue by mciprian13** [pytorch/glow#4522]
@jfix71 
I have a couple of questions about the quantization procedure. I am currently working with some backend specific nodes and I want to know some parts of the Glow philosophy involving quantization.
1. How exactly are the `RescaleQuantized` nodes merged during the optimizations? For example assume we have two nodes A->RescaleQuantized->B where A is the preceding node and B is the node following the `RescaleQuantized`.
   - Is the `RescaleQuantized` node merged in the output type of the preceding node (A)?
   - Is the `RescaleQuantized` node merged in the input type of the following node (B)?
   - Is it the same thing? If not, why choosing one and not the other?

2. When the CPU specific node `CPUMaxSplat` is created from a `Max(x, Splat)` for the quantized version, since the `CPUMaxSplat` implementation requires the input/output quantization parameters to be the same, a `RescaleQuantized` node is **pulled from the input** of the node.
   - Similar question: why a `RescaleQuantized` is pulled from the input of the node and not from the output? Is it the same and if not, why one and not the other?

3. During the quantization procedure, since the implementation for `MaxPool` requires the input/output quantization parameters to be the same, a `RescaleQuantized` node is **pulled from the output** of the node (here I might be wrong because the code is not very easy to read so it could be the input).
   - Same question here: why input and not output or viceversa? Also if it is different from point 2) (which seems at this point) again why?

Sorry to bother you but I have these questions for a long time ...
Thanks!

**Comment by jfix71** [comment]
> How exactly are the RescaleQuantized nodes merged during the optimizations? For example assume we have two nodes A->RescaleQuantized->B where A is the preceding node and B is the node following the RescaleQuantized.

There's a little bit of both. I think ideally we will merge them into the following node B, since it's essentially a no-op. We do also merge into the preceding node A, but this changes the numerics of the op -- e.g. if the Rescale is to a wider quantized range than the original output of the op then we will be less precise but have a larger range of values that can be represented. So I think merging to the following node is preferable (not sure how we handle which happens first right now, it might not be handled well).

> Similar question: why a RescaleQuantized is pulled from the input of the node and not from the output? Is it the same and if not, why one and not the other?

> Same question here: why input and not output or viceversa? Also if it is different from point 2) (which seems at this point) again why?

I don't think it really matters for either for these. We're not doing any calculations here, this is essentially just selecting between multiple values, so I think whether we rescale before or after doesn't make a difference.
