### ISSUE TITLE
[Graph] Transpose layout question

### ISSUE THREAD

**Issue by mciprian13** [pytorch/glow#4550]
@shajrawi Can you please explain the following lines of code?
https://github.com/pytorch/glow/blob/ae8d3a313871c53ea1bdbf63a6541dc5eebd7208/lib/Graph/Graph.cpp#L1199-L1216
I don't understand a couple of things:
- if the layout of the input tensor is unknown (ANY_LAYOUT) how can you decide the layout of the transposed tensor based on the shuffle? The logic should make no assumptions in this case for the output tensor right?
- why the layout is the property of the node when it should be a property of the Tensor/NodeValue? NHWC/NCHW/etc should be a property of the input/output!
- I don't understand the need for assigning NHWC/NCHW attributes when the Transpose node (and many other) should be viewed generic enough to process e.g. sound, sensor data, etc for which there is no H/W interpretation of any dimension.
- I don't understand the added value of the layout verification layer in Glow? All the importers are able to create consistent graph without any verification ...

The problem I'm currently having is that I create some constants with ANY_LAYOUT attribute and I apply a transpose with some shuffle and use the transposed tensor as a Conv2D input (data has no H/W dimension interpretation because is time series data). The layout verification fails saying that there is a mismatch between canonical and expected layout for that tensor for Conv2D (the Transpose operator decides which is the layout for the transposed tensor while it shouldn't).

Over time this layout thing feature mostly created problems than solving. One proposal would be to deactivate it until a more generic functionality is put in place.

**Comment by shajrawi** [comment]
* `ANY_LAYOUT` is not unknown, it is a "don't care" layout. for example elementwise operations
* There's an issue to make the layout property of the tensor / node value instead of the node that is up for grabs as i mentioned: https://github.com/pytorch/glow/issues/3790
* There's a markdown document that describes why we need to verify layouts and some of the rationale here https://github.com/pytorch/glow/blob/master/docs/TensorLayout.md
this code detected and fixed multiple bugs in the graph optimizer BTW. and we do need to know the input layout if say Caffe2 supports both NHWC and NCHW for an operation.
Helping catch problems / bugs early on is much easier than ignoring correctness verification and hoping for the best. the time spent detecting issues that may be due to wrong layouts or, worse, detecting a Glow compiler optimization bug is way longer than the inconvenience experienced by having it on.

**Comment by mciprian13** [comment]
Closing this issue.
