### ISSUE TITLE
[GraphOptz] Improve EliminateSliceConcat optimization

### ISSUE THREAD

**Issue by mciprian13** [pytorch/glow#4628]
Stumbled over this when compiling some GRU network:
![image](https://user-images.githubusercontent.com/29785908/85297703-c540ff80-b4ab-11ea-98c3-32decf8a8480.png)
So the slicing is done over dimension 0 (resulting in singular dimensions) and the concatenation along dimension 1 but in this particular case all the Slice and Concat node should be eliminated and replaced with a Reshape.

**Comment by Squadrick** [comment]
I'm working on this issue, I'll open a PR soon. This is the approach I'm taking:

`EliminateSliceConcat` only handles the case when the `Slice`s and `Concat` are along the same dimension. I'm changing it to track all consecutive `Slice`s along *some* dimension. If the dimension of slicing is the same as the dimension of concat, it'll use the pre-existing logic. If the dimension of slicing is different, the multiple consecutive `Slice`s can be replaced with a single `Slice` + `Reshape`. 

In the posted example, the above graph will turn into:
```
PH -> Slice ((0, 0, 0)...(4, 5, 6)) -> Reshape -> Concat -> Result
```
Since the `Slice` uses the entire input, and `Concat` only has a single input, it should be reduced to:
```
PH -> Reshape -> Result
```
@jfix71 Does GraphOptimizer handle the last two optimizations?
1. `Slice` across the entire input is a no-op, and should be removed.
2. `Concat` with a single input should be removed.

I looked at `docs/Optimizations.md`, but couldn't find the pertinent info:
```
  * Optimization of concat nodes

    This optimization merges multiple consequent concat nodes into a single concat
    node.
```

**Comment by jfix71** [comment]
@Squadrick Thanks for the explanation! Our `Optimizations.md` is definitely a bit out of date.

> `Slice` across the entire input is a no-op, and should be removed.

I'm actually not sure about this one, but it would be very simple to add if it's missing.

> `Concat` with a single input should be removed.

Yep, this one we definitely have here, which runs as part of `OptimizeConcatNodes`:
https://github.com/pytorch/glow/blob/94cd0b162a68e170aab97743b9c5c83963da8242/lib/Optimizer/GraphOptimizer/GraphOptimizer.cpp#L2432-L2435

**Comment by Squadrick** [comment]
> > `Slice` across the entire input is a no-op, and should be removed.
> 
> I'm actually not sure about this one, but it would be very simple to add if it's missing.
> 

Let me check this. If the optimization doesn't exist, I'll create an issue and fix it in a subsequent PR. 


> Yep, this one we definitely have here, which runs as part of `OptimizeConcatNodes`:
> https://github.com/pytorch/glow/blob/94cd0b162a68e170aab97743b9c5c83963da8242/lib/Optimizer/GraphOptimizer/GraphOptimizer.cpp#L2432-L2435

Oops, not sure how I missed this. Thanks for pointing it out!
