### ISSUE TITLE
Regarding PR #4867/68

### ISSUE THREAD

**Issue by anujgupt-github** [pytorch/glow#4912]
Hi @jfix71 :
I had a question about #4867  and #4868  
Are we heading in a direction to support externally quantized networks, to accept Quantization Params via external file, as an alternative to PGQ?
I studied these and this is what I could gather.

Also, is there updates to Quantization methods which are being worked upon?
Could you please comment on this, and if yes, please share some more light on the upcoming changes.  It will really help

**Comment by jfix71** [comment]
Hi @anujgupt-github -- so prior to those PRs we already did support externally quantized networks, e.g. see in the Caffe2ModelLoader "Int8FC", "Int8Conv", "Int8Quantize", etc. These ops are loaded as already quantized, outside of Glow.

In general we want to support any form of quantized networks, whether quantized inside or outside Glow (or even a mix if desired!). The quantization parameters may be generated however the user wants/defines in these cases -- I think that's usually at least guided by profiling to some extent.

Back to those PRs -- in general, yes, the motivation of those PRs is to be able to load a model that has quantization params provided from outside of Glow. The PRs allow for:

- Loading an already-quantized Caffe2 network, but ignoring the actual quantization params that are provided, loading using unique dummy quantization params instead
- Running Glow graph optimizations, but skipping those optimizations which would create new quantization parameters
- Serializing the final optimized model (at the Glow Node level) using Glow fully custom ONNX

Then we can later on reload this AOT optimized Glow ONNX model, along with the same Caffe2 network we originally loaded (except perhaps with different/new quantization params), and swap in these new quantization parameters into the Glow graph in place of the dummies. Then we can skip all Glow optimizations (since they have already been performed AOT) and continue with lowering the IR to further compile.

Some of our quantization methods are not open source, and I do not know the plans for what will or won't be open sourced.

In general I think the code in the PRs would be mostly reusable if we wanted to support this for other loaders like for ONNX, torch_glow, TFLite, etc.

**Comment by anujgupt-github** [comment]
Thanks a lot for your clarification, @jfix71 !
