### ISSUE TITLE
how can i use 3D-stacked memory and Process in memory with glow

### ISSUE THREAD

**Issue by imiiii** [pytorch/glow#4918]

**Comment by jfix71** [comment]
Hi @imiiii -- this is a pretty broad question. Glow tends to focus more on higher level SW optimizations -- it depends on the specific backend how much Glow should actually do. For some backends (e.g. CPU backend) we rely on LLVM to lower down to machine code/binaries. For others (e.g. NNPI backend) we pass an optimized graph down to another SW stack to further lower to machine code/binaries.

So in general, your question really should be targeted to individual backends and what they support. If LLVM supports such architectures, or the backend itself is targeting an architecture with such features, then they support it. So I'm not sure it's a meaningful question to whether Glow "supports" them -- if the backend being targeted does, then to an extent Glow does too, but not because core Glow is doing anything special here.
