### ISSUE TITLE
[Quantization] Make quantization parameters part of the constant weights

### ISSUE THREAD

**Issue by mciprian13** [pytorch/glow#5244]
@opti-mix @jfix71 
We have an internal usecase in which we want the following:
- Pre-compile a given quantized model (say TensorFlowLite) to a bundle and link it as part of the target run-time (the target is an MCU)
- We have some high-level front-end tools capable to retrain the **same model** with **different data**
- What we want is to update the model at run-time without re-compiling the run-time application:
  - In principle this would consist only in changing the model weights (since the model is the same and so should be the bundle) but for quantized models the quantized parameters are embedded in the bundle program and since a retraining changes the quantization parameters then we need also to update them as well
- Therefore what we need is to make the quantization parameters part of the weights buffer so they are dynamically read at run-time. This provides the flexibility we need. Some side effects would be that we lose the constant propagation for them.

So I have two questions:
1. Technically how hard does this seem to do and what (if any) technical problems do you see?
2. How open are you to have this modification in the upstream?

**Comment by jfix71** [comment]
I haven't looked much at the lower level details of bundling recently, so it's hard for me to comment on specifics there, @opti-mix can probably give a better answer. I imagine there will be some issues with the quantization parameter updating in the bundle though. AFAIK those are seen as constants by the kernels in libjit when they're compiled, so you'd need to add some sort of new compilation mode where the quantization parameters are seen as data and can be mapped to the right kernels at runtime. You'd additionally need to do the compilation with some sort of dummy quantization parameters (see below) or somehow disable optimizations that depend on comparing quantized types.

Aside from that, I can tell you that we do support something a little similar to this for the NNPI backend, but not for bundling, and only to skip rerunning high level graph optimizations. To do this we have this concept of constant folding replaying where save all const folding subgraphs as part of the model serialized to Glow ONNX, without the weights. Then when we get the new model we rerun the const folding subgraphs before continuing with compiling the model. And to support quantization parameters changing, when we first load the model before saving the ONNX file we do it using unique "dummy quantization parameters", and then when we load the actual model later with real quantization parameters we swap in the real quantization parameters instead of the dummy quantization parameters.

Since you're needing this with bundling, I am assuming that you're interested in an environment where you can't do the full recompilation only skipping graph optimizations. You could try to reuse some of the constant folding replaying functionality somehow, where you'd essentially save two models -- one to do const folding (only once when you get the update), and the other to do actual inference.

**Comment by mciprian13** [comment]
@jfix71 Thanks for your reply. Indeed I need this method for AOT mode. Basically I can have a full recompilation of the bundle but I need the guarantee that the same model but with different weights and quantization parameters is compiled into the same bundle object (program) but with a different file of weights and quantization parameters such that the bundle object does not need to be re-integrated (re-linked) into the application but only the weights file can be changed.
@opti-mix Do you have an opinion on the questions 1) and 2)?
