### ISSUE TITLE
glow/utils/imagenet-process.py could not work

### ISSUE THREAD

**Issue by miloee** [pytorch/glow#5764]
I tried to use imagenet-process.py to convert imagenet datasheet to png.
The command is "python3 ../glow/utils/imagenet-process.py *.JPEG processed/". The parser does not support.

And then I used the following command: “ls *.JPEG | xargs -I{} python3 ../glow/utils/imagenet-process.py {} processed/”. The result is "AttributeError: 'Image' object has no attribute 'unsqueeze'".

At the end, I tried "ls *.JPEG | xargs -I{} python3 ../glow/utils/imagenet-process.py {} processed/ --normalize". It works well.

So I believe that "normalize" mode could work.

**Comment by whiteking64** [comment]
About the first command, the following worked the parsing (but not image processing):
```
python ../utils/imagenet-process.py "../tests/images/imagenet/*.png" ./processed --normalize
```
(Please replace the image dir as necessary)
You need a quotation for setting `input` arg, because the character '*' is expanded by the shell.

`--normalize` mode is by default `False`.
In this case, the final type of `processed_im` is `PIL.Image`.
Since `unsqueeze` is a torch function, this cause the assertion error in your second command (Also in the above command without `--normalize`).

Your third command (the same as the above command and you don't need `ls` and `xargs` any more) still can fail.
This happens when the input glob images are PNG format (RGBA).
https://github.com/pytorch/glow/blob/c5bb4407df4ce8959a8d66073bbaf82b584dd8b9/utils/imagenet-process.py#L51
The variable `im` needs to be updated, as the `convert` function does not change the variable in-place.
