### ISSUE TITLE
NodeSplitting SegFault

### ISSUE THREAD

**Issue by glowbucky** [pytorch/glow#5789]
splitNode method throws segfault. I am in “Debug” mode, and using “resnet-runtime” network as the input.

```
for (auto &node : F->getNodes())
    {
      std::vector<glow::Node *> splitNodes;
      if(node.getNumResults() > 0)
      {  
        auto dims = node.dims(0);
        if(dims.size() == 4)
        {
          if(dims[3]/VW > 1)
          {
            std::cout << static_cast<std::string>(node.getName()) << "\n";
            ASSIGN_VALUE_OR_FATAL(splitNodes, glow::splitNode(&node, SplitNodeByNumChunks({ShapeNHWC::DimC},{dims[3]/VW})));
          }
        }
      }       
    }
```

@mciprian13

**Comment by mciprian13** [comment]
@glowbucky The problem is understandable although not obvious.
Looking in the source code comment here:
https://github.com/pytorch/glow/blob/a9a20240648180ede25e832acd6a9f2aa56859a2/include/glow/Optimizer/GraphOptimizer/NodeSplitting.h#L293-L299
The function deletes the original node after splitting it as a way to clean-up the mess. This means the node iterator gets screwed up:
```
for (auto &node : F->getNodes())
```
You should try alternatively to use the function `splitNodes` which has the right way of iterating the nodes.
Or you could use the iterator in a slightly different form to avoid this problem:
https://github.com/pytorch/glow/blob/a9a20240648180ede25e832acd6a9f2aa56859a2/lib/Optimizer/GraphOptimizer/NodeSplitting.cpp#L1421-L1424

**Comment by mciprian13** [comment]
@glowbucky Just as a confirmation did the above instructions solve the problem? Thanks!

**Comment by JUNSUNGKIM99** [comment]
@glowbucky  Hi, i tried to execute node split option. But, i didn't know how to use this optimization option...
How you do this option on resnet? 

Thanks

**Comment by glowbucky** [comment]
@JUNSUNGKIM99 Unlike other optimizations, there is no pass for nodesplitting. To use it you have to iterate through the graph and select the node you want to split and pass it to the nodesplitting api along with options. like in

> ```
> auto &nodes = F->getNodes(); 
> for (auto it = nodes.rbegin(), e = nodes.rend(); it != e;) { 
>   Node *node = &*(it++);
>       std::vector<glow::Node *> splitNodes;
>       if(node.getNumResults() > 0)
>       {  
>         auto dims = node.dims(0);
>         if(dims.size() == 4)
>         {
>           if(dims[3]/VW > 1)
>           {
>             std::cout << static_cast<std::string>(node.getName()) << "\n";
>             ASSIGN_VALUE_OR_FATAL(splitNodes, glow::splitNode(&node, SplitNodeByNumChunks({ShapeNHWC::DimC},{dims[3]/VW})));
>           }
>         }
>       }       
>     }
> ```

**Comment by JUNSUNGKIM99** [comment]
@glowbucky Thank you for your response. But i wonder where i implement this code you represented... 
I think, in graphoptimizer.cpp??
